# Generated by Django 2.1.2 on 2019-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('current', models.TextField(max_length=10000)),
            ],
        ),
    ]
