# Generated by Django 2.1.2 on 2019-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0002_auto_20190812_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='callectorgames',
            name='appId',
            field=models.TextField(default='', max_length=100),
        ),
    ]
