# Generated by Django 2.1.2 on 2019-08-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0003_callectorgames_appid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callectorgames',
            name='appId',
        ),
    ]
