# Generated by Django 2.1.2 on 2019-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0004_remove_callectorgames_appid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CALLectorGamesHighScores',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
