# Generated by Django 2.1.2 on 2019-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0005_callectorgameshighscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CALLectorGamesScores',
            fields=[
                ('appId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
