# Generated by Django 2.1.2 on 2019-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0007_auto_20190813_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callectorgamesscores',
            name='namespace',
        ),
        migrations.AlterField(
            model_name='callectorgamesscores',
            name='score',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
