# Generated by Django 2.1.2 on 2019-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CALLectorGames',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('laststate', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='CALLectorGamesHighScores',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CALLectorGamesScores',
            fields=[
                ('score', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
